server:
  port: 8888

spring:
  profiles:
    active: '@spring.active@'

knife4j:
  # 开启增强配置
  enable: true
  # 开启生产环境屏蔽
  #  production: true
  setting:
    # 是否显示文档中的搜索框，默认为true，即显示
    enableSearch: true
    # 对于调试中的请求参数是否缓存进行开启配置，该参数默认为true
    enableRequestCache: true
    # 动态参数
    enableDynamicParameter: true
    # 是否不显示Knife4j默认的footer，默认为true(显示)
    enableFooter: false
    # 是否自定义Footer，默认为false(非自定义)
    enableFooterCustom: true
    # 自定义Footer内容,支持Markdown语法
    footerCustomContent: zgh
  basic:
    enable: false
    username: zgh
    password: zgh